package methodsAndInterfaces

func Main() {
	methods()
	methodsFuncs()
	methodsContinued()
	methodsPointers()
	methodsPointersExplained()
	indirection()
	indirectionValues()
	methodsWithPointersReceivers()
	interfaces()
	interfacesAreSatisfiedImplicitly()
	interfaceValues()
	interfaceValuesWithNil()
	// nilInterfaceValues()
	emptyInterface()
	// typeAssertions()
	typeSwitches()
	stringer()
	exerciseStringer()
	errors()
	exerciseErrors()
	tourReader()
	exerciseReader()
	exerciseRotReader()
	images()
	// exerciseImages()
}
