basics:
	gcc `pkg-config --cflags gtk+-3.0` -o basics basics.c `pkg-config --libs gtk+-3.0`
helloworld:
	gcc `pkg-config --cflags gtk+-3.0` -o helloworld helloworld.c `pkg-config --libs gtk+-3.0`
grid:
	gcc `pkg-config --cflags gtk+-3.0` -o grid grid.c `pkg-config --libs gtk+-3.0`
clean:
	rm -rf *.o basics helloworld grid